[package]
name = "agents"
description = "Control plane agent"
version = "1.0.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

[[bin]]
name = "core"
path = "core/src/server.rs"

[[bin]]
name = "jsongrpc"
path = "jsongrpc/src/server.rs"

[lib]
name = "common"
path = "common/src/lib.rs"

[[bin]]
 name = "agent-ha-node"
 path = "ha-node/src/main.rs"

[dependencies]
anyhow = "1.0.44"
rpc =  { path = "../../rpc"}
common-lib = { path = "../../common" }
utils = { path = "../../utils/utils-lib" }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
chrono = "0.4.19"
structopt = "0.3.23"
tokio = { version = "1.20.1", features = ["full"] }
tonic = "0.5.2"
futures = "0.3.21"
serde_json = "1.0.82"
async-trait = "0.1.51"
dyn-clonable = "0.9.0"
snafu = "0.6.10"
lazy_static = "1.4.0"
humantime = "2.1.0"
state = "0.5.2"
http = "0.2.5"
paste = "1.0.5"
reqwest = "0.11.4"
parking_lot = "0.12.1"
itertools = "0.10.1"
grpc = { path = "../grpc" }
once_cell = "1.9.0"
indexmap = "1.8.0"
k8s-openapi = { version = "0.15.0", features = ["v1_20"] }
kube = { version = "0.74.0", features = ["derive"] }
tokio-udev = { version = "0.8.0" }
nvmeadm = { path = "../../utils/dependencies/nvmeadm" }
futures-util = { version = "0.3.21" }
tokio-stream = { version = "0.1.9" }
crossbeam-queue = "0.3.6"

# Tracing
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.17.4"
opentelemetry = { version = "0.17.0", features = ["rt-tokio-current-thread"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = [ "env-filter" ] }
opentelemetry-semantic-conventions = "0.9.0"

[dev-dependencies]
deployer-cluster = { path = "../../utils/deployer-cluster" }
actix-rt = "2.7.0"
actix-web = { version = "4.1.0", features = ["rustls"] }
url = "2.2.2"
once_cell = "1.8.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.140"
